apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: config-web
      image: anshuldevops/kubernetes-web:1.10.6
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
      - name: NAME  # Notice that the case is different here
                                     # from the key name in the ConfigMap.
        valueFrom:
            configMapKeyRef:
              name: configmap-secret        # The ConfigMap this value comes from.
              key: name # The key to fetch.


      - name: LASTNAME
        valueFrom:
            configMapKeyRef:
              name: configmap-secret 
              key: lastname

