apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume
spec:
  containers:
  - image: redis
    name: test-redis
    volumeMounts:
    - mountPath: /volume
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
